### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by Gnomey123** [taralika/google-voice-desktop#1]
When logging on with my Google account, it brings up this image:
![image](https://user-images.githubusercontent.com/34148010/85906440-50880100-b7dc-11ea-8375-b4bd11810a07.png)

When clicking "Learn more", and scrolling down, this message comes up for developers

![image](https://user-images.githubusercontent.com/34148010/85906507-8e852500-b7dc-11ea-9c2f-a12af1691192.png)

**Comment by greenmaze** [comment]
Same for me on Windows 10.

**Comment by taralika** [comment]
Thanks for reporting this. Please try the [latest release](https://github.com/taralika/google-voice-desktop/releases/tag/v1.2) and see if it gets fixed.
