### ISSUE TITLE
Windows version not working as intended.

### ISSUE THREAD

**Issue by lazyb5** [taralika/google-voice-desktop#2]
The icon is not the voice icon it's default electron icon. And the counter doesn't work. Has been like this for every version. Thought it was a user agent log in issue. But with the new version that fixes that these issue still persist.

**Comment by taralika** [comment]
This app is not being maintained actively. You can now make any website act as an app directly through Chrome: In Chrome on your PC/Mac, open the website e.g., voice.google.com then go to the browser menu (3 dots in top right), choose "More Tools" > "Create Shortcut" - Make sure to select "Open as window" - and now you'll get Voice to open in its own window like an app. Pin the icon to your desktop/app bar for quick access.
