### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by conformist1** [taralika/google-voice-desktop#4]
Hi there! Not sure how easy it would be to make a version with dark mode, but the brightness is so strong! Would really appreciate it 😊

Running on MacOS 11.1

**Comment by taralika** [comment]
@conformist1 you can try using https://github.com/Jerrkawz/google-voice-desktop-app - seems to have dark themes.

**Comment by conformist1** [comment]
@taralika Thank you!! Sorry to bother with this when the other one was right there!
