### ISSUE TITLE
can you make the data folder be under the program, not the roaming folder

### ISSUE THREAD

**Issue by 8090s** [taralika/google-voice-desktop#5]
Hello,
can you make the data folder be under the program, not the roaming folder?

**Comment by taralika** [comment]
This app is not being maintained actively. You can now make any website act as an app directly through Chrome: In Chrome on your PC/Mac, open the website e.g., voice.google.com then go to the browser menu (3 dots in top right), choose "More Tools" > "Create Shortcut" - Make sure to select "Open as window" - and now you'll get Voice to open in its own window like an app. Pin the icon to your desktop/app bar for quick access.
