### ISSUE TITLE
M1 / arm64 support?

### ISSUE THREAD

**Issue by seanbperiod** [taralika/google-voice-desktop#6]
Can you update to add native support for M1? 

Thanks!

**Comment by taralika** [comment]
@seanbperiod you don't need my app anymore. Just go to voice.google.com in Chrome and you can create a shortcut/app that opens in its own window and you can pin its shortcut/icon to your dock just like any app. Detailed instructions are here: https://www.hellotech.com/guide/for/how-to-create-a-desktop-shortcut-to-a-website

**Comment by seanbperiod** [comment]
Thanks, I tried that, but for some reason, the page doesn't refresh properly when clicking anywhere, and it also adds much extra space above the window, one for the page name, and then another for the title bar - Additionally, it's just like opening a new tab in a separate window. I liked that with your version, it ran as a separate process, and the title bar was nicely embedded within the web canvas.
<img width="1200" alt="Screen Shot 2022-01-10 at 2 05 39 PM" src="https://user-images.githubusercontent.com/8443498/148824391-e1543187-1690-4764-ba3b-6b6ad0af6043.png">

**Comment by taralika** [comment]
Mine looks fine.. make sure you are on latest macOS/Chrome versions and try again?
![voice-chrome-app](https://user-images.githubusercontent.com/46954145/148833940-098a92bc-d021-4ee2-a766-e5069dfa09fa.png)
